export const goals = [
  "Ripagare il debito di gratitudine verso i miei genitori, approfondire la fede e rilanciare l'azione di diffusione della Legge tra i giovani. Realizzare una vita gioiosa e dedida al benessere personale e di tutti. Veder crescere i mie piccoli nipotini. Far sbocciare relazioni profonde e sincere di amicizia.",
  "Portare Senzatomica sul mio territorio di residenza ",
  "Aprire il mio cuore e sviluppare sempre più coraggio per sostenere e vincere nella mia vita e insieme a capitolo Biella-Livorno-Santhià. \nPortare a ricevere il Gohonzon almeno 3 nuovi amici di cui 1 giovane",
  "Che mia moglie e mia figlia possano riprendono a praticare e assolutamente un nuovo membro giovane entro la fine dell’anno!",
  "Decido di diventare profondamente felice basando la mia via sul legame maestro-discepolo con Sensei Ikeda",
  "Rinnovare il voto e la determinazione per la pratica per gli altri",
  "avere coraggio di affrontare qualsiasi tipo di attacco e non farsi sviare da nulla, sostenere tutte le persone e soprattutto giovani e futuro. \nregalare al mio maestro una vittoria grandissima del nostro capitolo e personale e volare in alto in alto in alto ",
  "Portare una grande esperienza di vita e di lavoro ",
  "Essendo passato da pochissimo alla Divisione Ginkgo dopo 18 anni nel gruppo giovani, ora come giovane membro della Divisione Ginkgo determino di portare la freschezza e la determinazione dei giovani nella Divisione Ginkgo, e di fare da collante tra giovani e adulti, e soprattutto di continuare a sostenere i giovani ora più che mai, e continuare ad allenare i giovani successori per garantire un futuro luminoso ai miei figli e a tutti i giovani.",
  "Ripagare il mio debito di gratitudine verso la mia vita,la vita dei compagni di fede, e la felicità di tutti x mantenere fede al mio voto come il mio maestro!",
  "La regione Liguria ha il grande obiettivo di trovare un Kaikan più bello e accogliente.\nMi sto sforzando di fare ancora più shakubuku e almeno 2 ore di daimoku al giorno per realizzare questo obiettivo \nBuon incontro a tutti i membri della Divisione Ginkgo italiani ",
  'Una giovane compagna di fede che pratica da quando aveva 16 anni si è laureata il 20 u.s. con 110 e lode. In calce alla tesi ha scritto "A Daisaku Ikeda, faro costante della mia vita, e alla grande famiglia della Soka Gakkai, grazie con tutto il mio cuore. Senza la pratica buddista non avrei mai trovato la mia strada". Questo è il vero valore che possiamo esprimere! Al motto "Una famiglia Soka per ogni giovane" ho lanciato la mia sfida personale: anche mio figlio sarà un gu felice e discepolo di Ikeda Sensei entro la fine del corso! ',
  "Portare in ogni attività il cuore del Maestro per dare l'opportunità ad ogni membro di creare e rafforzare il suo legame con Sensei ed in questo modo ogni persona potrà avere solide radici su cui sviluppare la propria felicità",
  "Crescere nella azienda dove lavoro economicamente diventando manager di un gruppo di 10 giovani!!! Crescita esponenziale del Capitolo Oliveta a Sesto Fiorentino consegnando 28 Gohonzon!!! Mi miglioro ancora di più nel suonare il Basso Elettrico, e con i mie due gruppi vado in giro per la Toscana quest’anno a suonare ed il prossimo anno in tutta Italia. Arrivare in finale e Vincere con la band degli Alterna la competizione di X-Factor nel 2026 😃🙏♥️",
  "Risolvere un problema mio di lavoro, realizzare e seguire nuovi shakubuku,  realizzare Zaimu e incoraggiare la città di salerno",
  "OBIETTIVO CAPITOLO NUOVA ERA GENOVA Che tutti i giorni della settimana ci sia una casa in cui i membri della Divisione Ginkgo del Capitolo Nuova Era possano recitare assieme 1 ora di Daimoku per Kosen Rufu",
  "Che tutti i giorni della settimana ci sia una casa in cui i membri della Divisione Ginkgo del Capitolo Nuova Era possano recitare assieme 1 ora di Daimoku per Kosen Rufu",
  "Esperienza sul lavoro",
  "La crescita del capitolo Saragozza affinche ogni uomo diventi felive e crei successori...",
  "Alla fine del corso vorrei provare la stessa determinazione di Sensei Ikeda",
  "Sostenere tutto  il Capitolo Visconti  Milano crescita della Divisione Ginkgo e giovani che tutti  i partecipanti  realizzano grandi esperienze di fede",
  "Smettere di fumare e prendermi cura della mia salute per rispettare la sacralità della mia vita. ",
  "Crescere sempre di più nella azienda dove lavoro, coltivare sempre più legami di amicizia con tutti i colleghi e le persone che si interfacciano con la mia vita, puntando al dialogo valoroso e alla felicità di ogni individuo ❤️",
  "Smettere di fumare. Prendermi cura della mia salute e avere rispetto della sacralità della vita mia e altrui.",
  "Smettere di fumare. Avere cura della mia salute e rispettare la sacralità della mia vita.",
  "Smettere di fumare. Rispettare la sacralità della mia vita. ",
  "Crescita del capitolo signoria con 1 giovane nuovo per ogni gruppo.. ",
  "Riportare una grande vittoria al nostro maestro ",
  "Rivitalizzare tutta la mia pratica e diventare campione di incoraggiamento e vitalità! Terminare la mia carriera in modo luminoso e mostrarmi grato e generoso verso tutti.",
  " 2 nuovi membri giovani e realizzare gli scopi dei gruppi Liguria 3",
  "La felicità di tutti i partecipanti all'incontro e la determinazione di realizzare una crescita dei giovani tornati nelle nostre regioni ",
  "Crescita del Capitolo Oliveta con emergere di nuovi successori nei gruppi, settore e nel capitolo. Consegna entro il 31/12/2025 di 30 Gohonzon. Crescita lavorativa e di stipendio, diventando manager nella mia azienda di un nuovo ufficio composto da 10 giovani a cui farò shakubuku ed inizieranno a praticare. ",
  "Carriera lavorativa, livello superiore a lavoro.",
  "Con alla base la determinazione e volontà di realizzare gli Obiettivi 2025 per la felicità dei membri alcuni punti sintetici per me importanti: 1) Diventare un buon Discepolo di Sensei; 2) Continuare a trasmettere alle future generazioni la grandezza e lo Spirito di Sensei, (come da mia domanda a un corso in Giappone e risposta del Vice direttore Ishiguro; 3) Diventare un ottimo psicologo a sostegno dei genitori e dell'età evolutiva",
  "Tutti i partecipanti siano felici e realizzino grandi esperienze ",
  "Resettare e ripartire... sempre meglio ",
  "Sostenere tutte le persone del Capitolo Savona Ovest  e costruire un profondo legame con ognuno di loro.\nSostenere il settore Valbormida perchè diventi un Capitolo\nimaparare a volermi veramente bene ",
  "Una maggiore partecipazione attiva di tutta la Divisione Ginkgo, e che aumenti il loro desiderio di studiare e approfondire la conoscenza di qs buddismo per poterlo applicare alla propria vita e diventare felici",
  "acquisite e condividere il potere assoluto del Gohonzon per far progredire più velocemente kosen-rufu nella mia zona",
  "ACQUISIRE E CONDIVIDERE LA CONVINZIONE ASSOLUTA NEL POTERE DELLA FEDE PER FAR PROGREDIRE KOSEN RUFU NELLA MIA ZONA ",
  "Vincere sulle mie debolezze e sfiducia per Kosen Rufu \nFar crescere un uomo nella fede entro il 3 maggio.",
];
